### ISSUE TITLE
Operator credentials

### ISSUE THREAD

**Issue by DaFray31** [offen/deployment#4]
Hello,
This question is probably a dumb question, but with this installation, what are the email and password of the operator ? 

Regards

**Comment by m90** [comment]
After starting your instance for the very first time there is a web form available at `/setup` that you can use to create your first account and user.

Alternatively you can run the `offen setup` command in the container https://docs.offen.dev/running-offen/using-the-command/#offen-setup

**Comment by DaFray31** [comment]
Oh, yeah thanks, i didn't see !
Thanks a lot !
